### ISSUE TITLE
Cinder 0.8.6

### ISSUE THREAD

**Issue by zaherj** [wieden-kennedy/Cinder-KCB2#16]
Hi Guys,

I just wanted to point out that the currect Cinder-KCB2 doesn't work with the leatest version of Cinder 0.8.6

any advise on how to make it work?

Thanks

**Comment by vijtad** [comment]
I am getting same error.

Were you able to solve this.

Thanks

**Comment by wouterverweirder** [comment]
Had the same issue. You need to use Cinder from the master branch, not the precompiled 0.8.6 (which is  almost a year old).

**Comment by vijtad** [comment]
Thank you.

I am able to progress further using master branch.
Now I am getting the following link error like 

Error	38	error LNK2019: unresolved external symbol _GetFaceModelTriangles@8 referenced in function "public: __thiscall Kinect2::Device::FaceData::FaceData(struct IKinectSensor *,float *)" (??0FaceData@Device@Kinect2@@QAE@PAUIKinectSensor@@PAM@Z)

**Comment by vijtad** [comment]
I was able to compile successfully after doing following changes to code generated by ToolBox

1. kinect2.cpp 
     Replace
     face.mMesh->appendVertices( &iter->mFaceModelVertices[ 0 ], sFaceModelVertexCount );

    with

    face.mMesh->appendPositions( &iter->mFaceModelVertices[ 0 ], sFaceModelVertexCount );

    as appendVertices is removed and replaced with appendPositions.

2. CinderProjectApp.cpp
  Add 

     #include "cinder/gl/Draw.h"

at the top, to resolve the error on following line 

   ci::gl::draw( tex, tex->getBounds(), getWindowBounds() );
